server:
  port: 8082

spring:
  application:
    name: department-service
  datasource:
    url: jdbc:mysql://localhost:3306/department_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root         # Remplace par ton utilisateur MySQL
    password:  # Remplace par le vrai mot de passe MySQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
