server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/projects/**
        - id: role-service
          uri: lb://role-service
          predicates:
            - Path=/roles/**
        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/skills/**
        - id: office-service
          uri: lb://office-service
          predicates:
            - Path=/offices/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info,health
